[data]
name = 'Jruing'
newitem = 'test111'
newitem2 = 'test222'
numbers = [1, 2, 3, 4, 5, 6]
prod = false

[data.info]
name = 'John'

[database]
port = 3306
user = 'root'

[server]
host = 'localhost'
port = 8080
